export const ALL_TAGS = [
  { value: "lifestyle", label: "Lifestyle" },
  { value: "food", label: "Food" },
  { value: "travel", label: "Travel" },
  { value: "health", label: "Health" },
  { value: "fitness", label: "Fitness" },
  { value: "music", label: "Music" },
  { value: "books", label: "Books" },
  { value: "movies", label: "Movies" },
  { value: "tv-shows", label: "TV Shows" },
  { value: "news", label: "News" },
  { value: "sports", label: "Sports" },
  { value: "gaming", label: "Gaming" },
  { value: "art", label: "Art" },
  { value: "science", label: "Science" },
  { value: "technology", label: "Technology" },
  { value: "history", label: "History" },
  { value: "culture", label: "Culture" },
  { value: "automobile", label: "Automobile" },
  { value: "career", label: "Career" },
  { value: "guide", label: "Guide" },
  { value: "fashion", label: "Fashion" },
];
